apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sdzg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-sdzg@sha256:017f58bdf92055948ac1a168b69b44a17463f6109a2bc9c78cab4999a7818a5c
        name: my-nodejs
        resources: {}
status: {}
